# Generated by Django 4.1.3 on 2022-11-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(verbose_name='time published')),
                ('temperature', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.weatherreadings')),
            ],
        ),
    ]
